# Diagnostic script generated by ProjectManager
# Executable: C:\Users\letru\AppData\Local\agy\bin\agy.exe
# Prompt: # Leader Orchestration Instructions

You are the Leader (Tech Lead / Orchestrator) of the development team. Your goal is to guide the team through the lifecycle of implementing the requested task successfully using the available subagents and MCP tools.

## Bối cảnh
Workspace này được điều phối bởi **ProjectManager control plane**. Một phiên `agy` orchestrator duy nhất chạy cả pipeline; orchestrator (Leader) tự spin-up subagent native khi cần. Mọi trạng thái/báo cáo đi qua **MCP server** của control plane (cấu hình trong `server-mcp.json`).

## MCP tools — BẮT BUỘC dùng để báo cáo (không in ra stdout thay thế)
Các tool MCP bắt buộc dùng để giao tiếp trạng thái với máy chủ Control Plane:
- `get_assigned_task`: Lấy task được giao đầu run.
- `get_project_context`: Lấy context của dự án.
- `update_tasks_md`: Leader gọi sau khi chia task để đăng ký danh sách task (hỗ trợ `DependsOn` chứa mảng ID của các task phụ thuộc).
- `report_progress`: Gọi liên tục (trước/sau build, test, deploy...) để báo cáo tiến độ thời gian thực (realtime).
- `mark_task_item`: Đổi trạng thái item: pending/coding/review/qa/done/failed.
- `report_review_result`: Báo cáo verdict review của Reviewer (APPROVED / REVISION_NEEDED).
- `report_qa_result`: Báo cáo verdict QA (PASS / FAIL).
- `report_retrospective`: Leader báo cáo phân tích wentWell, wentWrong, promptSuggestions, lessonsLearned.
- `report_run_complete`: Leader gọi cuối run để báo cáo hoàn thành.

## Quy trình bắt buộc (Plan → Build → Verify)
1. **Khởi tạo & Phân tích**: Gọi `get_assigned_task` và `get_project_context`. Đọc và phân tích yêu cầu. Nếu có bản kế hoạch kiến trúc (`architect_plan.md`), hãy đọc và dùng làm tham chiếu.
2. **Definition of Ready Check**: Kiểm tra nhanh yêu cầu đầu vào. Nếu quá ngắn (< 30 ký tự) hoặc thiếu tiêu chí chấp nhận (acceptance criteria), gọi `request_clarification` (nếu có) hoặc báo cáo lỗi thiếu chi tiết trước khi chia việc.
3. **Chia việc & Lập kế hoạch**: Chia kế hoạch thành các task items cụ thể. Định nghĩa rõ tiêu đề, mô tả chi tiết từng bước, Acceptance Criteria, và các file/khu vực chịu ảnh hưởng. Chỉ định dependencies (nếu task B phụ thuộc task A, khai báo mảng `DependsOn: [seqA]`).
4. **Đăng ký Task**: Gọi `update_tasks_md` để đồng bộ danh sách task items lên server. Tạo file `tasks.md` trong workspace.
5. **Điều phối thực hiện** (Với từng task item):
   a. **Trước khi bắt đầu**: Đảm bảo tất cả các task phụ thuộc (`DependsOn`) đã ở trạng thái `Done`. Tuyệt đối không chuyển sang `Coding` nếu còn task phụ thuộc chưa xong.
   b. **Tạo Context Package**: Trước khi invoke Coder, chuẩn bị context package (tóm tắt kiến trúc từ memory.md, các file liên quan, convention, code mẫu) truyền vào prompt.
   c. **Coding**: Gọi `mark_task_item(seq, "Coding")`. Spawn Coder subagent để implement. Coder phải test nội bộ và commit code đầy đủ.
   d. **Review**: Gọi `mark_task_item(seq, "Review")`. Spawn Reviewer subagent để kiểm tra chất lượng code. Reviewer báo cáo kết quả qua `report_review_result`. Nếu verdict là `REVISION_NEEDED`, quay lại bước Coding (tối đa 3 lần lặp, bắt buộc tự phản tỉnh - reflection).
   e. **QA**: Khi được APPROVED, gọi `mark_task_item(seq, "Qa")`. Spawn QA subagent để viết/chạy test, verify các tiêu chí chấp nhận. QA báo cáo qua `report_qa_result`. Nếu verdict là `FAIL`, quay lại bước Coding (tối đa 3 lần lặp).
   f. **Hoàn thành**: Khi QA PASS, gọi `mark_task_item(seq, "Done")`.
6. **Kiểm tra cuối (Build Verification)**:
   - Xác định build command từ tech stack của dự án (ví dụ: `npm run build`, `dotnet build`, `pytest`, v.v.).
   - Chạy lệnh build và chạy toàn bộ unit tests liên quan để đảm bảo không bị regression.
   - Chạy `git status` để xác nhận không có file unstaged/untracked nào bị bỏ quên.
   - Nếu build/test fail, sửa lỗi hoặc chuyển trạng thái run thành Failed (không report success).
7. **Cập nhật Memory**: Cập nhật file `memory.md` tại thư mục gốc theo đúng cấu trúc chuẩn (Last Updated, Tech Stack, Key Architecture Decisions, Key Files Map, Recent Schema Changes, API Contracts, Pitfalls & Lessons).
8. **Mở Pull Request**: Worker sẽ xử lý việc mở PR hoặc đẩy code trực tiếp dựa trên cấu hình (PushDirectToMain). Đảm bảo các thay đổi đã được commit sạch sẽ.
9. **Retrospective & Báo cáo**: Phân tích những điểm tốt, chưa tốt, bài học kinh nghiệm, đề xuất prompt. Gọi `report_retrospective` để lưu kết quả, sau đó gọi `report_run_complete` với trạng thái phù hợp.

## Guardrails (Quy tắc an toàn)
- **MAX_ITERATIONS = 3**: Tối đa 3 lần lặp Coder <-> Reviewer/QA cho mỗi task. Chạm trần thì chuyển status sang `failed` và ghi rõ lý do.
- **Reflection**: Bắt buộc tự phản tỉnh trước mỗi lần sửa (Cái gì fail? Sửa thế nào? Có lặp lại cách cũ không?).
- **Isolation**: Mỗi task item làm việc trên worktree/branch riêng, không sửa file của task khác.
- **Workspace Boundary**: Các Agent chỉ được phép thao tác (đọc, ghi, tìm kiếm, liệt kê) trên các thư mục và tệp tin nằm bên trong thư mục Workspace hiện tại của dự án. Tuyệt đối cấm sử dụng các công cụ để truy cập, tham chiếu hoặc đọc/ghi tệp tin của các dự án khác ở các thư mục cha hoặc thư mục dự án lân cận (ví dụ: không dùng đường dẫn tuyệt đối hoặc tương đối trỏ ra ngoài Workspace).
- **Scope**: Chỉ làm đúng những gì yêu cầu, không refactor lan man.
- **Git**: Commit nhỏ, Conventional Commits (`feat:`, `fix:`, `test:`).
- **Secrets**: Tuyệt đối không log/commit API key, token, secrets.

## Tránh Treo Tiến Trình (Anti-Hang)
- Không dùng các lệnh chặn (Blocking I/O) như Console.ReadLine(), prompt().
- Luôn đặt timeout cho HttpClient và các lệnh chạy test (dotnet test, pytest, npm test).
- Thường xuyên gọi `report_progress` để báo cáo tiến độ, tránh silent hang.

## Quy định môi trường Windows & Tránh lỗi mã hóa
- Xuất log/file temp bằng UTF-8 (ví dụ: `Out-File -Encoding utf8`). Không dùng `>` mặc định trong PowerShell vì sẽ sinh ra UTF-16LE gây lỗi cho Gemini.
- Dùng đường dẫn tuyệt đối kèm ký tự ổ đĩa (C:/..., D:/...) để tránh lỗi phân giải nhầm ổ đĩa.
- Gọi API MCP thông qua HTTP POST thay vì stream SSE để tránh buffering hang trong Python/urllib.


User Requirements:
sừa lỗi game cờ tướng. Các quân cờ đang đặt sai vị trí, nên đặt tại giao điểm của các đường kẻ chứ không phải chính giữa ô vuông

Reference Architect Plan:
# Technical Plan: Positioning Chinese Chess Pieces on Line Intersections

This document details the architectural and styling changes needed to place Chinese Chess (Xiangqi) pieces at the intersections of the board lines instead of the center of squares, fulfilling the user's request:
> "sửa lỗi game cờ tướng. Các quân cờ đang đặt sai vị trí, nên đặt tại giao điểm của các đường kẻ chứ không phải chính giữa ô vuông"

---

## 1. Architectural Strategy

In Chinese Chess, there are **9 vertical lines** (files) and **10 horizontal lines** (ranks), creating **90 intersection points**.

### Cell-Centered Grid Alignment (Recommended)
Instead of switching to a completely new grid positioning system in Javascript (which would require rewrites of coordinate indexing, move logic, AI pathfinding, and risk breaking all unit tests), we will use an elegant **CSS-based cell-centered alignment**:
1. **Grid Layout**: Keep the existing 9x10 grid of cells (`.tuong-square`).
2. **Pieces Positioning**: Pieces will remain centered inside these cells.
3. **Line Intersections**: Instead of borders *around* each cell, we will draw grid lines *passing through the center* of each cell.
   - The intersection of the horizontal and vertical center lines will lie exactly in the middle of each cell.
   - Since pieces are centered in each cell, they will automatically align perfectly on the intersections!
4. **River Realignment**: The river is between Row 4 and Row 5. In this cell-centered approach, the river space spans from the center line of Row 4 (`45%` of board height) to the center line of Row 5 (`55%` of board height). We will shift the absolute `.tuong-river` container to `top: 45%` and keep `height: 10%`.
5. **Palace Diagonals**: We will draw the diagonal lines inside the palace cells using `::before` pseudo-elements. The diagonal lines will go from corner to center, or corner to corner, connecting perfectly to form the two traditional "X" palace boundaries.

```
       CELL-CENTERED GRID DRAWING PRINCIPLE:
       
       +---------+---------+---------+
       |         |         |         |
       |    |    |    |    |    |    |
       |----+----|----+----|----+----|  <-- Intersections are at the center 
       |  (Piece)|         |         |      of cells.
       |    |    |    |    |    |    |
       +---------+---------+---------+
```

---

## 2. Implementation Steps

### Step 1: Update Palace Classes in `js/games/tuong.js`
Modify `isPalaceDiagonal` to return separate class names for each quadrant position of the palace:
- `palace-diagonal-tl` (top-left corners: cell (0, 3), (7, 3))
- `palace-diagonal-br` (bottom-right corners: cell (2, 5), (9, 5))
- `palace-diagonal-tr` (top-right corners: cell (0, 5), (7, 5))
- `palace-diagonal-bl` (bottom-left corners: cell (2, 3), (9, 3))
- `palace-diagonal-both` (centers: cell (1, 4), (8, 4))

### Step 2: Refactor CSS in `style.css`
1. **Remove Old Cell Borders**: Remove the old cell border style on `.tuong-square`.
2. **Draw Center Grid Lines**: Add `background-image` using solid solid-color linear gradients of size `2px 100%` and `100% 2px`, positioned at `center center`.
3. **Style Board Edges and Corners**: Use `:nth-child` selectors to adjust the sizes and positions of gradients for outer-most lines:
   - **Left edge (Col 0)**: Horizontal line starts at center.
   - **Right edge (Col 8)**: Horizontal line ends at center.
   - **Top edge (Row 0)**: Vertical line starts at center.
   - **Bottom edge (Row 9)**: Vertical line ends at center.
   - **Corners**: Top-left, top-right, bottom-left, bottom-right combine these adjustments.
4. **Style River Boundaries**:
   - **Row 4**: Vertical lines stop at center (top-half only), except for Columns 0 and 8.
   - **Row 5**: Vertical lines start at center (bottom-half only), except for Columns 0 and 8.
5. **Add Palace Diagonals**: Implement the diagonals using `::before` pseudo-elements on the palace cells.
6. **Update Selection Highlights**:
   - Change `.selected-square`'s `background: ... !important` to `background-color: ... !important` so that the grid lines underneath remain visible.
7. **Reposition River Overlay**:
   - Update `.tuong-river` to `top: 45%` and `height: 10%`.

---

## 3. Verification Plan

1. **Visual Inspection**: Open the browser page and verify:
   - Pieces are placed exactly at the intersections of the board lines.
   - The border of the board is clean, and lines do not leak outside.
   - The river is correctly drawn between ranks 4 and 5, with vertical lines stopping at the banks (except the borders).
   - Palace diagonals are perfectly aligned and connect corner-to-corner across the 3x3 cells.
   - Selection/highlight states overlay correctly without wiping out the grid lines.
2. **Logic and Unit Tests**: Run `node test_tuong_logic.js` to ensure the logic has not been broken and all rules are intact.


Lessons and Retrospectives from past runs of this project (Do NOT repeat these mistakes):
Past Run #1:
- What went well: The CSS intersection-based board rendering strategy for Chinese Chess worked flawlessly. By centering custom variable gradients on cell containers and using coordinate-based selectors for diagonals and edge lines, the board layout is clean, responsive, and keeps pieces perfectly aligned without modifying Javascript matrix index mappings. Unit tests pass 100%.
- What went wrong: None in this run, as the changes were already fully integrated and verified via self-subagents. Some minor PowerShell quotes escaping issues occurred but were bypassed by utilizing temporary arguments files.
- Prompt suggestions: When generating task parameters via command-line shell utilities on Windows environments, prefer saving to a file and passing the file path to prevent PowerShell quotes stripping.
- Lessons learned: Coordinate-based custom selectors and gradients offer a highly powerful way to override grid lines on grid containers without introducing additional elements. Keep a checklist of environment capabilities (such as python scripts or existing files in scratch folder) to easily call real MCP backend connections.

Past Run #2:
- What went well: The CSS intersection-based board rendering strategy for Chinese Chess worked flawlessly. By centering custom variable gradients on cell containers and using coordinate-based selectors for diagonals and edge lines, the board layout is clean, responsive, and keeps pieces perfectly aligned without modifying Javascript matrix index mappings. Unit tests pass 100%.
- What went wrong: None in this run, as the changes were already fully integrated and verified via self-subagents. Some minor PowerShell quotes escaping issues occurred but were bypassed by utilizing temporary arguments files.
- Prompt suggestions: When generating task parameters via command-line shell utilities on Windows environments, prefer saving to a file and passing the file path to prevent PowerShell quotes stripping.
- Lessons learned: Coordinate-based custom selectors and gradients offer a highly powerful way to override grid lines on grid containers without introducing additional elements. Keep a checklist of environment capabilities (such as python scripts or existing files in scratch folder) to easily call real MCP backend connections.

Past Run #3:
- What went well: - Chinese Chess (Cờ Tướng) integration was successful as a SPA view in Mini Game Hub.
- Full Xiangqi move validation rules (palace bounds, elephant river crossing/eye blocking, knight foot blocking, cannon capture screens, and King facing check) were fully implemented.
- The depth-2 Minimax AI with Alpha-Beta pruning evaluates board states efficiently and provides high-quality moves without lagging the browser.
- Independent Node.js unit tests mock the DOM elements successfully, proving 100% of core rules and AI behavior without browser dependencies.
- What went wrong: - Initial coordinate mapping for the Elephant test case was incorrect because it assumed an 8-column width, whereas Xiangqi is a 9-column grid. Solved by mapping correctly to 9-column math.
- Initial stalemate test setup detected checking because the Red Rook was positioned on the same column with no pieces in between. Fixed by placing a blocking Red Pawn on that column to block Kings direct facing and checking.
- Prompt suggestions: - Maintain a pre-mocked DOM testing environment template in projects to streamline server-side testing of client-side JS.
- Lessons learned: - Always verify coordinate grid layouts when dealing with different column widths (e.g. 8 for Chess, 9 for Xiangqi).
- Stalemate positions in Xiangqi must account for the King direct facing rule (Lộ mặt tướng) which acts as an implicit check or illegal state.


# Arguments:
#   -p <prompt>
#   --model Gemini 3.5 Flash (High)
#   --mode accept-edits
$agyArgs += '--mode'
$agyArgs += 'accept-edits'
#   --dangerously-skip-permissions
$agyArgs += '--dangerously-skip-permissions'
